-- Initial schema, generated from the JPA entities.
--
-- Databases created before the migrations existed are baselined at this version and skip it,
-- which is what `spring.flyway.baseline-on-migrate` is for. Every change from now on comes as a
-- new versioned script: Hibernate no longer alters the schema, it only validates it at start up.

CREATE TABLE users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_role     VARCHAR(255) CHECK (user_role IN ('ROLE_USER', 'ROLE_ADMIN', 'HIDDEN')),
  locked        BOOLEAN,
  enabled       BOOLEAN,
  gold          BOOLEAN,
  birth_date    TIMESTAMP(6),
  registered_date TIMESTAMP(6),
  nickname      VARCHAR(255),
  job           VARCHAR(255),
  height        BIGINT,
  email         VARCHAR(255),
  password      VARCHAR(255),
  description   VARCHAR
);

CREATE TABLE genders_ages (
  user_id       BIGINT NOT NULL PRIMARY KEY,
  gender        VARCHAR(255) CHECK (gender IN ('MAN', 'WOMAN', 'OTHER')),
  gender_search VARCHAR(255) CHECK (gender_search IN ('MAN', 'WOMAN', 'OTHER')),
  min_age       BIGINT,
  max_age       BIGINT,
  CONSTRAINT fk_genders_ages_user FOREIGN KEY (user_id) REFERENCES users
);

CREATE TABLE geolocations (
  user_id         BIGINT NOT NULL PRIMARY KEY,
  latitude        VARCHAR(255),
  longitude       VARCHAR(255),
  distance_search BIGINT,
  distance        BIGINT,
  CONSTRAINT fk_geolocations_user FOREIGN KEY (user_id) REFERENCES users
);

CREATE TABLE preferences (
  user_id          BIGINT NOT NULL PRIMARY KEY,
  alcohol_drinking VARCHAR(255) CHECK (alcohol_drinking IN ('NO', 'MAYBE', 'YES')),
  smokes           VARCHAR(255) CHECK (smokes IN ('NO', 'MAYBE', 'YES')),
  organised        VARCHAR(255) CHECK (organised IN ('NO', 'MAYBE', 'YES')),
  personality      VARCHAR(255) CHECK (personality IN ('INTROVERT', 'AMBIVERT', 'EXTRAVERT')),
  sport_practice   VARCHAR(255) CHECK (sport_practice IN ('NO', 'MAYBE', 'YES')),
  animals          VARCHAR(255) CHECK (animals IN ('NO', 'MAYBE', 'YES')),
  parenthood       VARCHAR(255) CHECK (parenthood IN ('NO', 'MAYBE', 'YES')),
  gamer            VARCHAR(255) CHECK (gamer IN ('NO', 'MAYBE', 'YES')),
  CONSTRAINT fk_preferences_user FOREIGN KEY (user_id) REFERENCES users
);

CREATE TABLE stats (
  user_id        BIGINT NOT NULL PRIMARY KEY,
  total_dislikes BIGINT,
  total_likes    BIGINT,
  total_matches  BIGINT,
  CONSTRAINT fk_stats_user FOREIGN KEY (user_id) REFERENCES users
);

CREATE TABLE pictures (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content         VARCHAR,
  is_main_picture BOOLEAN,
  fk_user_id      BIGINT NOT NULL,
  CONSTRAINT fk_pictures_user FOREIGN KEY (fk_user_id) REFERENCES users
);

CREATE TABLE notifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content    VARCHAR(255),
  link       VARCHAR(255),
  date       TIMESTAMP(6),
  seen       BOOLEAN,
  fk_user_id BIGINT NOT NULL,
  CONSTRAINT fk_notifications_user FOREIGN KEY (fk_user_id) REFERENCES users
);

-- Likes, dislikes and messages reference the accounts by identifier rather than by association:
-- the rows outlive neither user and are deleted explicitly when an account is closed.
CREATE TABLE likes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date        TIMESTAMP(6),
  fk_sender   BIGINT,
  fk_receiver BIGINT
);

CREATE TABLE dislikes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date        TIMESTAMP(6),
  fk_sender   BIGINT,
  fk_receiver BIGINT
);

CREATE TABLE messages (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content     VARCHAR,
  date        TIMESTAMP(6),
  sender      VARCHAR(255),
  fk_sender   BIGINT,
  fk_receiver BIGINT
);

-- Archive of the closed accounts, kept for the back office statistics.
CREATE TABLE deleted_accounts (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nickname        VARCHAR(255),
  email           VARCHAR(255),
  registered_date TIMESTAMP(6),
  deletion_date   TIMESTAMP(6),
  total_dislikes  BIGINT,
  total_likes     BIGINT,
  total_matches   BIGINT,
  deleted_by      VARCHAR(255)
);
