# Dev Configuration
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

PGHOST: localhost
PGPORT: 5432
PGDATABASE: pickme
PGUSER: postgres
PGPASSWORD: root
