# Dev Configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

DB_HOST: localhost
DB_PORT: 5432
DB_NAME: pickme
DB_USER: postgres
DB_PASSWORD: root
